# Generated by Django 3.2.2 on 2021-05-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_alter_drink_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
