# Generated by Django 3.2.2 on 2021-05-09 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_alter_drink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None),
        ),
    ]
