# Generated by Django 3.2.2 on 2021-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_alter_drink_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
